<script setup lang="ts">
import { computed } from 'vue'
import { withBase } from 'vitepress'
import intelligenceData from '../../generated/research-intelligence.json'
type Status='Waiting'|'Running'|'Completed'|'Blocked'|'Failed'|'Skipped'
type PipelineResult={id:string;label:string;label_zh:string;status:Status;due:number;checked:number;inaccessible:Array<{source:string;reason:string}>;failed:Array<{source:string;reason:string}>;signals:number;candidates:number;selected:number;rejected:number;coveragePercent:number;reason:string;reason_zh:string}
type ColumnResult={id:string;label:string;label_zh:string;decision:'Waiting'|'Selected'|'No Selection';signals:number;candidates:number;selectedItemId:string;selectedTitle:string;selectedTitle_zh:string;reason:string;reason_zh:string}
type Run={date:string;status:Status;reason:string;reason_zh:string;pipelines:PipelineResult[];columns:ColumnResult[]}
type Data={today:string;timezone:string;registryVersion:string;effectiveDate:string;registryPath:string;currentRun:Run}
const data=intelligenceData as Data;const props=withDefaults(defineProps<{lang?:'en'|'zh'}>(),{lang:'en'});const zh=computed(()=>props.lang==='zh');const run=computed(()=>data.currentRun)
const copy=computed(()=>zh.value?{kicker:'RESEARCH INTELLIGENCE SYSTEM V1.0',title:'研究情报雷达',lead:'AI 平台、GitHub 工程、论文与研究成果三条情报管线，共同服务数字员工、行业架构和开源工程三个板块。',pipelines:'三条情报管线',columns:'三栏选题结果',due:'应检查',checked:'已检查',inaccessible:'受限',signals:'信号',candidates:'候选',selected:'入选',noSelection:'未选题',waiting:'待执行',registry:'情报源明细',run:'今日扫描记录',effective:'生效日期',sourceNote:'完成标准是覆盖率和可追溯结果，不是强行找到一篇文章。',status:{Waiting:'待执行',Running:'运行中',Completed:'已完成',Blocked:'已阻塞',Failed:'失败',Skipped:'已跳过'}}:{kicker:'RESEARCH INTELLIGENCE SYSTEM V1.0',title:'Research Intelligence Radar',lead:'AI Platform, GitHub Engineering, and Published Research intelligence jointly serve the Digital Employee, Industry Architecture, and Open-source Engineering columns.',pipelines:'Three Intelligence Pipelines',columns:'Three-Column Decisions',due:'Due',checked:'Checked',inaccessible:'Restricted',signals:'Signals',candidates:'Candidates',selected:'Selected',noSelection:'No Selection',waiting:'Waiting',registry:'Intelligence Sources',run:"Today's Scan Record",effective:'Effective',sourceNote:'Completion is measured by source coverage and traceable outcomes, not by forcing an article.',status:{Waiting:'Waiting',Running:'Running',Completed:'Completed',Blocked:'Blocked',Failed:'Failed',Skipped:'Skipped'}})
const statusLabel=(s:Status)=>copy.value.status[s];const statusClass=(s:Status)=>`s-${s.toLowerCase()}`;const pipelineName=(i:PipelineResult)=>zh.value?i.label_zh:i.label;const pipelineReason=(i:PipelineResult)=>zh.value?i.reason_zh:i.reason;const columnName=(i:ColumnResult)=>zh.value?i.label_zh:i.label;const columnReason=(i:ColumnResult)=>zh.value?i.reason_zh:i.reason;const columnTitle=(i:ColumnResult)=>zh.value?i.selectedTitle_zh:i.selectedTitle;const columnStatus=(i:ColumnResult)=>i.decision==='Selected'?copy.value.selected:i.decision==='No Selection'?copy.value.noSelection:copy.value.waiting;const columnClass=(i:ColumnResult)=>i.decision==='Selected'?'s-completed':i.decision==='No Selection'?'s-skipped':'s-waiting';const repoUrl=(p:string)=>`https://github.com/joinwell52-AI/joinwell52/blob/main/${p}`;const registryPage=computed(()=>withBase(zh.value?'/zh/runtime/intelligence-sources':'/en/runtime/intelligence-sources'));const runPath=computed(()=>`research/intelligence/runs/${run.value.date.slice(0,4)}/${run.value.date.slice(5,7)}/${run.value.date}-intelligence.json`)
</script>
<template><section class="intel-radar"><div class="intel-shell"><header><div><span class="kicker">{{copy.kicker}}</span><h2>{{copy.title}}</h2><p>{{copy.lead}}</p></div><div class="meta"><b :class="statusClass(run.status)">{{statusLabel(run.status)}}</b><span>{{run.date}} · {{data.timezone}}</span></div></header><section class="panel"><div class="section-title"><h3>{{copy.pipelines}}</h3><small>{{copy.sourceNote}}</small></div><div class="pipeline-grid"><article v-for="item in run.pipelines" :key="item.id"><div class="card-head"><div><small>{{item.id.toUpperCase()}}</small><h4>{{pipelineName(item)}}</h4></div><b :class="statusClass(item.status)">{{statusLabel(item.status)}}</b></div><div class="coverage"><span><strong>{{item.checked}}</strong>{{copy.checked}}</span><span><strong>{{item.due}}</strong>{{copy.due}}</span><span><strong>{{item.inaccessible.length+item.failed.length}}</strong>{{copy.inaccessible}}</span></div><div class="bar"><i :style="{width:`${item.coveragePercent}%`}"></i></div><div class="metrics"><span><strong>{{item.signals}}</strong>{{copy.signals}}</span><span><strong>{{item.candidates}}</strong>{{copy.candidates}}</span><span><strong>{{item.selected}}</strong>{{copy.selected}}</span></div><p>{{pipelineReason(item)}}</p></article></div></section><section class="panel columns-panel"><div class="section-title"><h3>{{copy.columns}}</h3><small>{{copy.effective}} · {{data.effectiveDate}}</small></div><div class="column-grid"><article v-for="item in run.columns" :key="item.id" :class="`column-${item.id}`"><div class="card-head"><div><small>{{item.id.replaceAll('-',' ').toUpperCase()}}</small><h4>{{columnName(item)}}</h4></div><b :class="columnClass(item)">{{columnStatus(item)}}</b></div><h5 v-if="item.decision==='Selected'">{{item.selectedItemId}} · {{columnTitle(item)}}</h5><p>{{columnReason(item)}}</p><div class="metrics"><span><strong>{{item.signals}}</strong>{{copy.signals}}</span><span><strong>{{item.candidates}}</strong>{{copy.candidates}}</span></div></article></div></section><footer><a :href="registryPage">{{copy.registry}} ↗</a><a :href="repoUrl(runPath)">{{copy.run}} ↗</a></footer></div></section></template>
